name: "Build & Release Tank Survivor"
on:
  push:
    tags:
      - "v*" # This trigger runs when you push a version tag like v1.0.1

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: Export Game
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Godot Game
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}